### ISSUE TITLE
no way to suppress console log of copied files

### ISSUE THREAD

**Issue by clhuang** [swc-project/cli#111]
When run with --copy-files, the filenames of non-compilable files are output to the console. I'm not sure if this was even intended behavior, due to the way it was introduced in https://github.com/swc-project/cli/pull/32.

But even when run with `-q`, the output persists, which definitely seems like a bug.

**Comment by tmayr** [comment]
Seems like there's a lone console.log responsible for this, so it looks to me like it just made it through? doesn't look intentional

https://github.com/swc-project/cli/blob/master/src/swc/dir.ts#L80

@kdy1 would you safe its safe to remove?
