### ISSUE TITLE
Support JSONSchema property

### ISSUE THREAD

**Issue by Rawnly** [swc-project/cli#118]
It would be super nice to support the [`$schema`](schemastore.org) property inside `.swcrc` file.

```json
{
		"$schema": "http://json.schemastore.org/swcrc",
		...
}
```

The [schema url](http://json.schemastore.org/swcrc) already works fine, but when I try to run the cli I get 

```
    1: failed to deserialize .swcrc (json) file: unmatched data: 2:10
	2: unknown field `$schema`, expected one of ... 
```

![immagine](https://user-images.githubusercontent.com/16429579/154107218-e3cc2f47-7e92-49be-a9d2-baa37ecbd746.png)

**Comment by clouedoc** [comment]
I do not get this issue with the following versions:

```
@swc/cli: 0.1.57
@swc/core: 1.2.204
```

**Comment by Rawnly** [comment]
> I do not get this issue with the following versions:
> 
> ```
> @swc/cli: 0.1.57
> @swc/core: 1.2.204
> ```

It has been patched months ago
