### ISSUE TITLE
Source Map Format invalid

### ISSUE THREAD

**Issue by PSeitz** [swc-project/cli#12]
The source maps are emitted in a wrong format:

Example Output
```json
{
  "version": 3,
  "sources": [
    "// import { add } from './add';\r\n// export {add} from './add'\r\n\r\nconsole.log(\"start\")\r\nexport function add(num1: number, num2: number){\r\n    return num1 + num2;\r\n}\r\nconst res = add(3, 4);\r\n\r\nconsole.log(res)\r\n"
  ],
  "names": [],
  "mappings": ";;;;Q,G,G,G;A,E,6B;A,E,0B;A,O,C,G,E,K;S,G,C,I,E,I;W,I,G,I;;I,G,G,G,C,C,E,C;A,O,C,G,C,G",
  "file": "index.js"
}
```

According to https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit
```
"sources": ["foo.js", "bar.js"],
"sourcesContent": [null, null],
```
"sources" should not contain the content, but path to the original files

**Comment by kdy1** [comment]
I thunk it's related to https://github.com/getsentry/rust-sourcemap/pull/25

**Comment by PSeitz** [comment]
@kdy1 I don't see how they are related, this is a perfromance optimization and does not change the structure, but I guess this bug report should go to swc/core.

**Comment by PSeitz** [comment]
Moved to here
https://github.com/swc-project/swc/issues/707
I think I found the root cause, the sourcemap crate is called with the wrong parameters.
