### ISSUE TITLE
--only and --ignore clarity

### ISSUE THREAD

**Issue by josteph** [swc-project/cli#20]
It seems these two flags:
- --only
- --ignore

are not yet present in the cli [`handle`](https://github.com/swc-project/cli/blob/92df674e497222f90f6750eb316e485e26c7536f/src/swc/dir.ts#L41) function.

Let's say I want to avoid to compile every js files under `__tests__` folder. 
That means the command would look more or less like this:
```
swc -d dist --ignore '**/__tests__/**'
```

But in the output folder, I would still have the `__tests__` folder.

---

SWC version:
```
"@swc/cli": "0.1.36"
"@swc/core": "1.2.51"
```

I would be happy to open PR if you validate about this issue :)

**Comment by chyzwar** [comment]
I this is now supported by swcrc, "exclude": "(__tests__|__mocks__)", should we pass this options via cli as well ?

**Comment by chyzwar** [comment]
Once problem with using exclude in swcrc is that it would break in jest tests. If I add above exclude then @swc/jest will error in jest with 

```
cannot process file because it's ignored by .swcrc
```

see this build https://github.com/swc-project/cli/pull/32/checks?check_run_id=2713136059

**Comment by coffee377** [comment]
This issue was fixed in 0.1.54(#90), but still exists in 0.1.55.
In version 0.1.54, copying non-compilable files was not work(ignored files were not copied)

**Comment by r-guerin** [comment]
Hi guys, is there any update on the subject ? I am still struggling to ignore files through the `--ignore` arg using the 0.1.57.

**Comment by Naoto-Ida** [comment]
I'll also mention that the `--ignore` option isn't working for us (on latest `0.1.57`).
A workaround is to have 2 `.swcrc`, but this is not ideal :p

Our repo looks like:
```
📁 src
  📁 __tests__
  📁 components
```

And we're running `swc ./src/ -d lib --ignore src/**/__tests__/*.tsx`.

**Comment by tangye1234** [comment]
Any update? Now I can only have 2 `swcrc` for build and test. I have just turned my oss into swc based but now frustrated for this.

**Comment by caseykhuc** [comment]
The following solution should work. Summary: Override swc config for files that require `@swc/jest`.
```js
const swcConfig = JSON.parse(fs.readFileSync(`${__dirname}/.swcrc`, "utf-8"));

// ---
  transform: {
    ".+\\.ts$": [
      "@swc/jest",
      {
        ...swcConfig,
        exclude: [],
      },
    ],
  },
// ---
```
https://github.com/swc-project/jest/issues/62

[Document](https://jestjs.io/docs/configuration#transform-objectstring-pathtotransformer--pathtotransformer-object)

**Comment by cilvet** [comment]
Same problem. Neither "exclude" nor "ignore" options are working properly yet.

**Comment by kdy1** [comment]
@josteph Are you still willing to open a PR? If not, I'll work on it
