### ISSUE TITLE
`--ignore` and `--only` do not work

### ISSUE THREAD

**Issue by 3axap4eHko** [swc-project/cli#203]
When compiling code, option `--ignore` provided pattern does not go into the glob config. That said the following command will compile tests even if they are ignored,
```bash
swc src --ignore **/__tests__/**/*.ts -d build
```

**Comment by craigmiller160** [comment]
Yep, I just opened an issue on the same thing. It seems this has been a problem for a while. I'm shocked no one has fixed it yet.

**Comment by kdy1** [comment]
Can you try the new native CLI?

https://github.com/swc-project/swc/discussions/3859

**Comment by kdy1** [comment]
Closing in favor of https://github.com/swc-project/cli/issues/245

**Comment by kdy1** [comment]
Oops I did it in the wrong way

**Comment by kdy1** [comment]
@3axap4eHko Can you provide a repro?

**Comment by 3axap4eHko** [comment]
@kdy1 in this repo git@github.com:3axap4eHko/interoperability.git just try `yarn` and then `yarn swcx --help`

**Comment by kdy1** [comment]
I tried several things, but seems like the ignore option of the native CLI is not working well.

Relevant code: https://github.com/swc-project/swc/blob/f66da772202a6f065488fbabb7e0a9d9a2d7089d/bindings/swc_cli/src/commands/compile.rs#L160-L167

Can you file an issue on the main repository instead?

**Comment by kdy1** [comment]
@3axap4eHko 

This is the patch you should apply, regardless of the state of cli issues:
```diff

diff --git a/package.json b/package.json
index 638dd2e..0aaf316 100644
--- a/package.json
+++ b/package.json
@@ -8,7 +8,7 @@
     "inop": "bin/inop.js"
   },
   "scripts": {
-    "build": "rm -rf build && swc ./src -d build && rm -rf build/__tests__ && tsc --declaration --emitDeclarationOnly",
+    "build": "rm -rf build && swcx compile ./src --out-dir build && rm -rf build/__tests__ && tsc --declaration --emitDeclarationOnly",
     "test": "jest",
     "build:example": "(cd example && npm run build)",
     "test:example": "(cd example && npm run test)"
@@ -42,7 +42,7 @@
     "interoperability"
   ],
   "dependencies": {
-    "@swc/core": "^1.3.63",
+    "@swc/core": "^1.3.85",
     "commander": "^11.0.0",
     "fast-glob": "^3.2.12"
   },
diff --git a/yarn.lock b/yarn.lock
index 3386727..e90369b 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -676,7 +676,7 @@
   resolved "https://registry.yarnpkg.com/@swc/core-win32-x64-msvc/-/core-win32-x64-msvc-1.3.85.tgz#5c7f3f366804b512cf26e1731d8714f0409f1204"
   integrity sha512-ktxWOMFJ0iqKn6WUHtXqi4CS7xkyHmrRtjllGRuGqxmLmDX/HSOfuQ55Tm1KXKk5oHLacJkUbOSF2kBrpZ8dpg==
 
-"@swc/core@^1.3.63":
+"@swc/core@^1.3.85":
   version "1.3.85"
   resolved "https://registry.yarnpkg.com/@swc/core/-/core-1.3.85.tgz#36ce756854efa2320f601a2b3e1ca1096f8b3f16"
   integrity sha512-qnoxp+2O0GtvRdYnXgR1v8J7iymGGYpx6f6yCK9KxipOZOjrlKILFANYlghQxZyPUfXwK++TFxfSlX4r9wK+kg==

```

**Comment by 3axap4eHko** [comment]
@kdy1 I can confirm --ignore option does not work on `swcx` either
