### ISSUE TITLE
swc_ecma_lints E0554 `#![feature]` may not be used on the stable release channel

### ISSUE THREAD

**Issue by justinfriebel** [swc-project/cli#218]
I'm just installing the `swc_cli` for the first time and getting this error:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_lints-0.81.20/src/lib.rs:3:1
  |
3 | #![feature(box_patterns)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `swc_ecma_lints` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `swc_cli v0.91.40`, intermediate artifacts can be found at `/var/folders/wx/q60_3qcd38jcs82nqbz7_7s80000gn/T/cargo-installM0Y7lb`
```

**Comment by HeartyPorridge** [comment]
You need to install and use **rust nightly**.
Enter the command - **rustup default nightly**

**Comment by voltrevo** [comment]
It appears this was introduced here:
https://github.com/swc-project/swc/issues/7019

I'd like to stay on stable rust if possible. I'm going to try to figure out what version I need to go back to to do this.

@HeartyPorridge Do you know the project's stance on depending on rust nightly?

**Comment by bsunderhus** [comment]
@voltrevo , any news on this?

**Comment by voltrevo** [comment]
@bsunderhus Can't say I have any news :(... I'm not really the person to ask though.

**Comment by kdy1** [comment]
Closing as this is not a correct place for a such issue

**Comment by voltrevo** [comment]
@kdy1 Sorry about that. Where would be the correct place?
