### ISSUE TITLE
There is no reliable way to include/exclude files

### ISSUE THREAD

**Issue by craigmiller160** [swc-project/cli#245]
I have a typescript project and I am using the following swc config:

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "target": "es2018",
    "loose": false,
    "externalHelpers": false,
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  }
}
```

Then I run it with this command:

```
swc src --config-file ./configs/swc/.swcrc -C module.type=commonjs -d build --only **/*.{ts,mts,cts,tsx} --ignore **/*.d.{ts,mts,cts,tsx}
```

The problem is, the --only & --ignore properties don't work. It still grabs all the files, compiles them, and outputs them. The reason this is an issue is that I have some .d.ts files in my sources, and they get compiled into .d.js files. This is completely incorrect behavior.

I've tried --only/--ignore. I've tried the "exclude" property in the swcrc (which results in a parsing error of the swcrc). Nothing works.

I love what SWC can do in terms of its lightning-fast compilation, but from a configuration perspective it is just consistently painful to work with. I sincerely hope that there is work on a better, more reliable configuration system.

**Comment by kdy1** [comment]
Closing in favor of https://github.com/swc-project/cli/issues/245

**Comment by 3axap4eHko** [comment]
@kdy1 why did you close this one?

**Comment by kdy1** [comment]
@3axap4eHko See https://github.com/swc-project/cli/issues/245#issuecomment-1723622625
