### ISSUE TITLE
Add an option to process files in parallel with worker processes 

### ISSUE THREAD

**Issue by walkerburgin** [swc-project/cli#274]
It looks like `@swc/cli` processes files in parallel on the main thread ([here](https://github.com/swc-project/cli/blob/eaccf25bd7fa2d66497a26609118acef7acc5294/src/swc/dir.ts#L139-L167)). It should be significantly faster to process files using a pool of worker sub-processes. This is straightforward to implement using `@swc/core`, but it would be really nice to be able to integrate the official CLI into our build system instead of this little custom wrapper.

I tried this out for minification on a large internal project with ~2400 output files: 
* Running the CLI with `--sync` takes  ~3m24s
* Running the CLI in parallel mode takes ~2m28s
* Using a pool of 8 worker processes takes ~18s

Is this something the project would consider?

**Comment by kdy1** [comment]
Yes, of course
