### ISSUE TITLE
NestJS SWC v0.1.64 Compile Error: 'Cannot read properties of undefined (reading 'length')' 

### ISSUE THREAD

**Issue by GNURub** [swc-project/cli#278]
I am getting an error when compiling my application in nestjs with swc, it occurs in version 0.1.64, but not in 0.1.63. (Error Cannot read properties of undefined (reading 'length')). [Maybe here](https://github.com/swc-project/cli/commit/4f0bd60addf399a47be4f5c3f805073e2221c439#diff-dc05644f5a7f98a1a756a19dca85e9f46988f1271bef6e01f1c26886a511f08aR48)

**Comment by vlad-ostrovski** [comment]
the issue is here:
https://github.com/swc-project/cli/blame/4f0bd60addf399a47be4f5c3f805073e2221c439/src/swc/sources.ts#L48

`only` arrives here as undefined.. and so `only.length` crashes.
