### ISSUE TITLE
Changed output directory structure in 0.2.2

### ISSUE THREAD

**Issue by GNURub** [swc-project/cli#281]
[breaking changes](https://github.com/swc-project/cli/commit/3d4e6c77a03a4bbb6552608463af8a7528484aa9)

Configurations with "paths" alias generates a diferent output directory:
- v0.2.0 -> dist/
- v0.2.2 -> dist/src/

**Comment by kdy1** [comment]
https://github.com/swc-project/cli/commit/f87c850442d6beabbbc6dfd1ecee4bc895a65748 reverts the changes in `v0.2.2`

**Comment by ShogunPanda** [comment]
This was then reintroduced in `v0.3.0`.
Is there a way to get `v0.2.x` behavior in the latest version?

**Comment by kdy1** [comment]
You can use `v0.2.3`, but not in`v0.3.x`

**Comment by ShogunPanda** [comment]
Sorry, I'll rephrase: is there any option (or plan to add an option) in `v0.3.x` to get the same behavior?
If not, would you accept a PR for it?

**Comment by kdy1** [comment]
I'll accept a PR, but I'm not sure about the name of the option

**Comment by ShogunPanda** [comment]
Let's choose it together. Out of my mind I'm thinking about the following (in order of preference):

1. `--strip-leading-paths`
2. `--resolve-destination-paths`
3. `--strip-leading-destination-paths`

Do you like any of those? Or do you have any similar suggestion?

**Comment by kdy1** [comment]
I also prefer the first one

**Comment by imranbarbhuiya** [comment]
Hi, is there any way to pass this flag ` --strip-leading-paths` from `.swcrc`?

**Comment by ShogunPanda** [comment]
Not at the moment. I plan to implement this in #284.
