### ISSUE TITLE
(Bug?) Outdir adds "baseUrl" to directory structure as of V0.3.0

### ISSUE THREAD

**Issue by baskager** [swc-project/cli#282]
### When setting the baseUrl in `.swcrc` as such:
```json
{
    "jsc": {
        "baseUrl": "./src"
    }
}
```
###  ...And running `swc` with the `outdir` set like this:
```bash
npx swc --config-file .swcrc ./src -d dist
```

### I end up with an extra `/src/` in the outdir folder
![image](https://github.com/swc-project/cli/assets/5838517/8887866d-44e7-4e2d-b0e4-26e335d37d7c)

---
Is this a breaking change for `V0.0.3` or might this be a bug?
---

#### V0.2.3
![image](https://github.com/swc-project/cli/assets/5838517/7b3efcb0-e03d-42bf-8c25-216148845558)
#### V0.3.0 (wrapped in an additional `src` directory
![Screenshot from 2024-01-25 18-37-57](https://github.com/swc-project/cli/assets/5838517/376a5e24-6de4-4138-ad0f-cf83e0b3a712)

**Comment by baskager** [comment]
If it is intended behavior it does deviate from `tsc`.

This could cause issues for people. For instance: When one wants to generate type definitions (`.d.ts` files). This is not yet supported in `SWC`.

Above issues was actually our exact case, the new types were able to be imported from our packages as expected but the `.js` files were still outdated.

## e.g.

```bash
npx tsc --declaration --emitDeclarationOnly && npx swc --config-file .swcrc ./src -d dist
```

Would place the compiled `.js` files in `/dist/src/` and the corresponding type definitions in `/dist/`.

---

Breaking changes such as this come as kind of a surprise and lead to strange behavior after an update of NPM packages. In addition there is little communication about the breaking change which then turns it into a bit of a `needle-in-a-haystack` situation. Would love to brainstorm and help out on this point if you're on board with that +1: 

Thanks for taking the time reading my ramblings, much appreciated :relaxed:

**Comment by kdy1** [comment]
See https://github.com/swc-project/cli/issues/281

**Comment by kdy1** [comment]
Closing as fixed by https://github.com/swc-project/cli/pull/283.
You can use `--strip-leading-paths` to get the old behavior.
