### ISSUE TITLE
Verison `0.3.3` generates files with the `.undefined` extension

### ISSUE THREAD

**Issue by Gamote** [swc-project/cli#287]
I am using NestJS together with `@swc/cli`. This morning I have updated to the `0.3.3` from `0.3.2` and all the exported files are ending in the `.undefined` extension. For example what before was `dist/src/main.js` now it is `dist/src/main.undefined`.

I have rolled back to `0.3.2` and everything works as expected.

The bug must have been introduced in: https://github.com/swc-project/cli/commit/0e0d745c1c31d9148c2464ae624b1db012eb469e

**Comment by Gamote** [comment]
Found the issue, I am preparing a PR now.

**Comment by kdy1** [comment]
Should be fixed by `v0.3.4`

**Comment by Gamote** [comment]
@kdy1 Thank you for the quick response.

`v0.3.4` fixes the issue only if the consumer goes through the CLI.

If `dir.ts` is called directly, like many consumers do, we would experience the same issue, this is because prior `v0.3.2` we had the default extension inside `dir.ts`. So event tho' I think it is better to pass the correct arguments when you interact with those files directly, I see it as breaking change.

Will this be something that you like: https://github.com/swc-project/cli/pull/288?

**Comment by kdy1** [comment]
Yeap, it's what I like
