### ISSUE TITLE
wrong package in package.json

### ISSUE THREAD

**Issue by szhigunov** [swc-project/cli#3]
In package.json in dependencies I found mistyped dependency `loadsh`
```
"loadsh": "^0.0.3",
"lodash": "^4.17.11",
```

**Comment by ccouzens** [comment]
It looks like it got fixed and removed in this commit b74cfec64e89c184a0ceaac827669f241b785da3

**Comment by kdy1** [comment]
@szhigunov You can reinstall with `npm i --save-dev @swc/core @swc/cli `
