### ISSUE TITLE
--config with dot notation seems not working

### ISSUE THREAD

**Issue by HelloWorld017** [swc-project/cli#45]
## Issue
According to the documentation, by using the command `swc src -C module.type=commonjs`, it should transpile the code with `type` option set to be `commonjs`.

But, when I have used that command, it threw some error like
```
Argument at `2` is not JsBuffer

Caused by:
    unknown field `module.type` at line 1 column 100
```

## Suspect
When I have tried to fix the issue, I found out that [src/swc/options.ts#L230](https://github.com/swc-project/cli/blob/master/src/swc/options.ts#L230) only assigns the value to the top level configuration.

So I have changed that line to something like the following code, and I could find out that it transpiles successfully.
```js
const keyArray = key.split('.');
const options = keyArray
	.slice(0, -1)
	.reduce((config, currentKey) => {
		if (!config[currentKey]) {
			config[currentKey] = {};
		}

		return config[currentKey];
	}, swcOptions);

options[keyArray[keyArray.length - 1]] = value;
```

Now, I am curious whether this is the intended behavior or not.
Please let me know if I am using the swc cli inappropriately.

Thank you!

**Comment by heygrady** [comment]
This is a regression. Previously this was using `lodash/set`. The current code is broken.

See here: https://github.com/swc-project/cli/blame/95c8a228ff7679c286858b6f34b4e3d703d643fc/src/swc/options.ts#L215

I was using this to set the module type to commonjs.

```sh
swc --config module.type=commonjs src -d cjs --source-maps --copy-files
```

That generates a final config like this:

```js
{
  jsc: { parser: undefined, transform: {} },
  sourceMaps: true,
  sourceFileName: undefined,
  sourceRoot: undefined,
  configFile: undefined,
  'module.type': 'commonjs' // <-- this is clearly wrong
}
```

**Comment by heygrady** [comment]
Looks like it was broken with this PR: https://github.com/swc-project/cli/pull/32

**Comment by HelloWorld017** [comment]
Closing as the #48 has been merged. Thanks!
