### ISSUE TITLE
Not printing error detail when running `swc`

### ISSUE THREAD

**Issue by vjpr** [swc-project/cli#58]
When running `swc src -d lib -s` when there is an error I get this unhelpful message:

```
Failed to compile 4 files with swc.
Error: Failed to compile
    at initialCompilation (/Users/Vaughan/dev/fork/+swc/cli/lib/swc/dir.js:159:19)
    at async dir (/Users/Vaughan/dev/fork/+swc/cli/lib/swc/dir.js:219:5)
```

Here is the place that prints errors:

https://github.com/swc-project/cli/blob/c68ace2fb38a6e5a2df085a69360404525e309b0/src/swc/dir.ts#L132-L174

In the `sync` runner there are `console.log`s, but not in the async runner. If I add a `console.log(result)` it prints:

```
{
  status: 'rejected',
  reason: [Error: failed to process js file

  Caused by:
      0: failed to load config for file 'Real("src/foo/index.ts")'
      1: failed to read swcrc file (src/foo/index.ts)
      2: failed to deserialize .swcrc (json) file: syntax error: 17:3
      3: key must be a string at line 17 column 3] {
    code: 'GenericFailure'
  }
}
```

This error should be printed.

This error was caused by bad syntax in `.swcrc`:

```json
{
  "jsc": {
    "target": "es2020",
    "parser": {
      "syntax": "typescript",
      "tsx": true,
      "decorators": true,
      "dynamicImport": true
    },
    "baseUrl": "src",
    "paths": {
      "@src/*": [
        "*"
      ]
    }
  },
  module: {
    type: 'commonjs',
  }
}

```

**Comment by amatiasq** [comment]
No news here?

**Comment by ptboyer** [comment]
I just tried to get started with `swc` (@swc/core@1.2.111 and @swc/cli@0.1.51) and got stuck with a similar problem.

I haven't created a `.swcrc` yet, but just tried using `swc src --out-dir dist` and it failed without showing any errors about what went wrong: `Failed to compile 6 files with swc.`

Once I removed `--out-dir dist` to be `swc src` the errors were shown to me.
