### ISSUE TITLE
lib/**/*.ts should match lib/index.ts, but it does not

### ISSUE THREAD

**Issue by FrankFang** [swc-project/cli#64]
My file list:

```
lib
├── base.ts
├── databaseClient.ts
├── index.ts
└── test
    └── a.ts
```

run swc via yarn build (this is required step!)

```
$ yarn build
yarn run v1.22.10
$ swc -d dist lib/**/*.ts
[ 'lib/test/a.ts' ] # I add console.log(program.args) into node_modules/@swc/cli/lib/swc/options.js line 65 for debugging
Successfully compiled: 1 file with swc (5.71ms)
Done in 0.22s.
```

then I change the build script to `swc -d dist lib/*.ts lib/**/*.ts` , run again

```
$ yarn build
yarn run v1.22.10
$ swc -d dist lib/*.ts lib/**/*.ts
[
  'lib/base.ts',
  'lib/databaseClient.ts',
  'lib/index.ts',
  'lib/test/a.ts'
]
Successfully compiled: 4 files with swc (9.43ms)
Done in 0.20s.
```

but, when I run swc in zsh, the bug disappears:
```
$ npx swc -d dist lib/**/*.ts
[
  'lib/base.ts',
  'lib/databaseClient.ts',
  'lib/index.ts',
  'lib/test/a.ts'
]
Successfully compiled: 4 files with swc (9.45ms)
```

It looks like a bug of [commander](https://github.com/tj/commander.js).

**Comment by dangreen** [comment]
@FrankFang Hi. I don't think what swc supports globs. May be your shell environment is support globs and just replace them with files list? To pass globs directly to binary just wrap them into quotes.

```
npx swc -d dist "lib/**/*.ts"
```

**Comment by FrankFang** [comment]
yes, it depends on the shell env.
I use git bash for Windows.
