### ISSUE TITLE
Add code formatter/linter 

### ISSUE THREAD

**Issue by dangreen** [swc-project/cli#91]
@kdy1 Hi. How about adding code formatter (e. g. prettier)? I can help by opening PR with changes if you accept this idea.

Also, you can ping me if you need some help with other stuff. I have a great experience with TS/JS/web and open source projects.

**Comment by kdy1** [comment]
Of course, it's definitely in the scope of the project, for both of fomratter and linter.
Actually, there's WIP PR for linter, but I didn't have time to work on it.

I'd love to accept PRs :)
