### ISSUE TITLE
Empty output for latest swc/cli@0.1.54 

### ISSUE THREAD

**Issue by aelbore** [swc-project/cli#97]
### Input code

src/index.ts
```typescript
export function log() {
  return 'Hello World'
}
```

package.json script
```json
  "scripts": {
    "build": "swc ./src/index.ts -o ./dist/index.js"
  },
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "dynamicImport": true
    },
    "target": "es2020"
  }
}
```

### Expected behavior

it should have build output

### Version

@swc/cli@^0.1.54 and @swc/core@^1.2.120

### Additional context

This works when cli is at version 0.1.52

**Comment by kdy1** [comment]
Fixed by reverting https://github.com/swc-project/cli/commit/47135083bcc89a3dd3a2611cad5c87647c567610

**Comment by aelbore** [comment]
@kdy1 yes works fine when using 0.1.52, 
does it possible to publish new version to revert it? 

can we open this until the fixed will revert?

**Comment by kdy1** [comment]
I already published a new version

**Comment by aelbore** [comment]
@kdy1 great many thanks
